### ISSUE TITLE
Version 2017083000

### ISSUE THREAD

**Issue by amandadoughty** [wiris/moodle-qtype_wq#10]
We are unable to regrade wiris quizzes.

**This is the initial error and stack trace:**

Sorry! The system can not generate one of the questions of the quiz. 
Maybe there is a temporary connection problem right now. 
Maybe the question algorithm has a bug, and fails sometimes. 
Maybe it will fail always. 
Don't panic... 
You can retry the quiz, without penalty, just clicking Continue. 
You can also tell the Teachers that there is an issue with the question titled: 'Normal distribution 1'

More information about this error

×Debug info: 
Error code: wirisquestionincorrect
×Stack trace:
line 328 of /question/type/wq/question.php: moodle_exception thrown
line 169 of /question/type/multianswerwiris/question.php: call to qtype_wq_question->call_wiris_service()
line 216 of /question/type/multianswerwiris/question.php: call to qtype_multianswerwiris_question->set_shortanswer_matching_answers()
line 151 of /question/behaviour/adaptive/behaviour.php: call to qtype_multianswerwiris_question->grade_response()
line 95 of /question/behaviour/adaptive/behaviour.php: call to qbehaviour_adaptive->process_submit()
line 1233 of /question/engine/questionattempt.php: call to qbehaviour_adaptive->process_action()
line 1307 of /question/engine/questionattempt.php: call to question_attempt->process_action()
line 876 of /question/engine/questionusage.php: call to question_attempt->regrade()
line 379 of /mod/quiz/report/overview/report.php: call to question_usage_by_activity->regrade_question()
line 450 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->regrade_attempt()
line 307 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->regrade_attempts()
line 99 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->process_actions()
line 96 of /mod/quiz/report.php: call to quiz_overview_report->display()

**If I comment out the try and catch block in the function 'call_wiris_service' then the stack trace is:**

Exception - Remote exception: java.io.IOException: Connexion error while connecting with wiris kernel: Connection reset

More information about this error

×Debug info: 
Error code: generalexceptionmessage
×Stack trace:
line 38 of /question/type/wq/quizzes/lib/com/wiris/quizzes/wrap/QuizzesServiceWrap.class.php: HException thrown
line 315 of /question/type/wq/question.php: call to com_wiris_quizzes_wrap_QuizzesServiceWrap->execute()
line 169 of /question/type/multianswerwiris/question.php: call to qtype_wq_question->call_wiris_service()
line 216 of /question/type/multianswerwiris/question.php: call to qtype_multianswerwiris_question->set_shortanswer_matching_answers()
line 151 of /question/behaviour/adaptive/behaviour.php: call to qtype_multianswerwiris_question->grade_response()
line 95 of /question/behaviour/adaptive/behaviour.php: call to qbehaviour_adaptive->process_submit()
line 1233 of /question/engine/questionattempt.php: call to qbehaviour_adaptive->process_action()
line 1307 of /question/engine/questionattempt.php: call to question_attempt->process_action()
line 876 of /question/engine/questionusage.php: call to question_attempt->regrade()
line 379 of /mod/quiz/report/overview/report.php: call to question_usage_by_activity->regrade_question()
line 450 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->regrade_attempt()
line 307 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->regrade_attempts()
line 99 of /mod/quiz/report/overview/report.php: call to quiz_overview_report->process_actions()
line 96 of /mod/quiz/report.php: call to quiz_overview_report->display()

**Comment by wirismath** [comment]
We are very sorry for the delayed answer.
We would recommend that you update to the latest version and, if the issue persists, please contact us at support@wiris.com with the details.
Thanks.
