### ISSUE TITLE
'object' class has been deprecated

### ISSUE THREAD

**Issue by mudrd8mz** [wiris/moodle-qtype_wq#2]
```
'object' class has been deprecated, please use stdClass instead.

line 71 of /lib/setuplib.php: call to debugging()
line 105 of /question/type/wq/step.php: call to object->__construct()
line 193 of /question/type/shortanswerwiris/question.php: call to qtype_wirisstep->set_var()
line 67 of /question/type/shortanswerwiris/question.php: call to qtype_shortanswerwiris_question->get_matching_answer()
line 109 of /question/behaviour/deferredfeedback/behaviour.php: call to qtype_shortanswerwiris_question->grade_response()
line 57 of /question/behaviour/deferredfeedback/behaviour.php: call to qbehaviour_deferredfeedback->process_finish()
line 1233 of /question/engine/questionattempt.php: call to qbehaviour_deferredfeedback->process_action()
line 1271 of /question/engine/questionattempt.php: call to question_attempt->process_action()
line 839 of /question/engine/questionusage.php: call to question_attempt->finish()
line 167 of /question/preview.php: call to question_usage_by_activity->finish_all_questions()
```

Replacing the `$gc = new Object();` with `$gc = new stdClass();` seems to fix the issue for me.

**Comment by manuelwiris** [comment]
David, 
The new release (3.48.1.1020) fix the issue.

**Comment by AlexJB777** [comment]
I get a similar error using Moodle 3.2.7 and php 7.1.26, mysql 5.7.25 on Linux 
The question is where (what dir and file) can I change this?
"Replacing the $gc = new Object(); with $gc = new stdClass(); seems to fix the issue for me."
Thanks


'object' class has been deprecated, please use stdClass instead.
line 71 of /lib/setuplib.php: call to debugging()
line 176 of /blocks/configurable_reports/locallib.php: call to object->__construct()
line 185 of /blocks/configurable_reports/locallib.php: call to urldecode_recursive()
line 185 of /blocks/configurable_reports/locallib.php: call to urldecode_recursive()
line 226 of /blocks/configurable_reports/locallib.php: call to urldecode_recursive()
line 93 of /blocks/configurable_reports/reports/sql/report.class.php: call to cr_unserialize()
line 69 of /blocks/configurable_reports/viewreport.php: call to report_sql->create_report()
