### ISSUE TITLE
Tiny typo in English language string in qtype_wq

### ISSUE THREAD

**Issue by germanvaleroelizondo** [wiris/moodle-qtype_wq#4]
Hi,
When I was translating the Question types: WIRIS QUIZZES Commons question type plugin in AMOS, I noticed a strange-looking English language string:

wqsummary | qtype_wq
This adds a generic WIRIS question. Only for test purpose. It will be hide from here

I wonder if it should be 'hidden' insted of 'hide'

Thanks in advance for your help.

**Comment by reixarch** [comment]
Thanks German. We will solve it ASAP.
Gracias por tu ayuda.
