### ISSUE TITLE
fatal error : Cannot redeclare decode_html_entities()

### ISSUE THREAD

**Issue by jn-gautier** [wiris/moodle-qtype_wq#5]
Trying to install "Wiris Quizzes for Moodle" version 2017051000 on moodle 3.3 but get
Fatal error: Cannot redeclare decode_html_entities() (previously declared in /home/.../www/question/type/wq/lib.php:19) in /home/.../www/question/type/wq/db/upgrade.php on line 105

**Comment by manuelwiris** [comment]
@jn-gautier  Seems that the mehotd devode_html_entities are duplicated in upgrade.php and lib.php files. During this week we will upload a new version fixing this bug.

Thanks for your feedback.
